export const CREATE_THREAD_REQ = "CREATE_THREAD_REQ";
export const CREATE_THREAD_SUC = "CREATE_THREAD_SUC";
export const CREATE_THREAD_FAIL = "CREATE_THREAD_FAIL";

export const GET_THREAD_REQ = "GET_THREAD_REQ";
export const GET_THREAD_SUC = "GET_THREAD_SUC";
export const GET_THREAD_FAIL = "GET_THREAD_FAIL";

export const GET_ALL_THREADS_REQ = "GET_ALL_THREADS_REQ";
export const GET_ALL_THREADS_SUC = "GET_ALL_THREADS_SUC";
export const GET_ALL_THREADS_FAIL = "GET_ALL_THREADS_FAIL";

export const POST_COMMENT_REQ = "POST_COMMENT_REQ";
export const POST_COMMENT_SUC = "POST_COMMENT_SUC";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";

export const GET_COMMENTS_REQ = "GET_COMMENTS_REQ";
export const GET_COMMENTS_SUC = "GET_COMMENTS_SUC";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const UPDATE_COMMENT_REQ = "UPDATE_COMMENT_REQ";
export const UPDATE_COMMENT_SUC = "UPDATE_COMMENT_SUC";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";

export const UPDATE_THREAD_REQ = "UPDATE_THREAD_REQ";
export const UPDATE_THREAD_SUC = "UPDATE_THREAD_SUC";
export const UPDATE_THREAD_FAIL = "UPDATE_THREAD_FAIL";
