export const GET_ALL_PROJECTS_REQ = "GET_ALL_PROJECTS_REQ";
export const GET_ALL_PROJECTS_SUC = "GET_ALL_PROJECTS_SUC";
export const GET_ALL_PROJECTS_FAIL = "GET_ALL_PROJECTS_FAIL";

export const GET_PROJECT_REQ = "GET_PROJECT_REQ";
export const GET_PROJECT_SUC = "GET_PROJECT_SUC";
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL";

export const CREATE_PROJECT_REQ = "CREATE_PROJECT_REQ";
export const CREATE_PROJECT_SUC = "CREATE_PROJECT_SUC";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const UPDATE_PROJECT_REQ = "UPDATE_PROJECT_REQ";
export const UPDATE_PROJECT_SUC = "UPDATE_PROJECT_SUC";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";

export const DELETE_PROJECT_REQ = "DELETE_PROJECT_REQ";
export const DELETE_PROJECT_SUC = "DELETE_PROJECT_SUC";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const MANAGE_DEVELOPER_REQ = "MANAGE_DEVELOPER_REQ";
export const MANAGE_DEVELOPER_SUC = "MANAGE_DEVELOPER_SUC";
export const MANAGE_DEVELOPER_FAIL = "MANAGE_DEVELOPER_FAIL";
