export const USER_SIGNIN_REQ = 'USER_SIGNIN_REQ';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILURE = 'USER_SIGNIN_FAILURE';

export const USER_SIGNOUT = 'USER_SIGNOUT';
